# Generated by Django 4.1.7 on 2023-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_password_user_profile_pic_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
