# Generated by Django 4.1.7 on 2023-03-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.FileField(upload_to='plant image')),
                ('disease', models.CharField(max_length=500, null=True)),
                ('user_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'plant details',
            },
        ),
    ]
