# Generated by Django 4.1.7 on 2023-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_image',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant_image',
            name='prevent',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant_image',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
