# Generated by Django 4.1.7 on 2023-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_plant_image_desc_plant_image_prevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_image',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
