# Generated by Django 4.1.7 on 2023-03-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_plant_image_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_image',
            name='disease',
        ),
    ]
