# Generated by Django 4.1.7 on 2023-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_plant_image_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_image',
            name='prevent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plant_image',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
