# Generated by Django 4.1.7 on 2023-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_plant_image_prevent_alter_plant_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_image',
            name='s_img',
            field=models.FileField(null=True, upload_to='sup image'),
        ),
        migrations.AddField(
            model_name='plant_image',
            name='s_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant_image',
            name='s_name',
            field=models.TextField(null=True),
        ),
    ]
